// Generated by Selenium IDE
package testBasket;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class testSelenium {
       /* public WebDriver driver = new ChromeDriver();

        @Test
        public void uppgift2testautomatisering() {
            driver.get("https://membership.basketballengland.co.uk/NewSupporterAccount");
            driver.manage().window().setSize(new Dimension(1429, 802));
            driver.findElement(By.id("dp")).click();
            driver.findElement(By.id("dp")).sendKeys("07/07/1999");
            driver.findElement(By.id("member_firstname")).click();
            driver.findElement(By.id("member_firstname")).sendKeys("John");
            driver.findElement(By.id("member_lastname")).click();
            driver.findElement(By.id("member_lastname")).sendKeys("Doe");
            driver.findElement(By.name("EmailAddress")).click();
            driver.findElement(By.id("member_emailaddress")).sendKeys("Johndoe3@email.com");
            driver.findElement(By.id("member_confirmemailaddress")).click();
            driver.findElement(By.id("member_confirmemailaddress")).sendKeys("Johndoe3@email.com");
            driver.findElement(By.id("signupunlicenced_password")).click();
            driver.findElement(By.id("signupunlicenced_password")).sendKeys("Megastrong");
            driver.findElement(By.id("signupunlicenced_confirmpassword")).click();
            driver.findElement(By.id("signupunlicenced_confirmpassword")).sendKeys("Megastrong");
            driver.findElement(By.cssSelector(".md-checkbox > .md-checkbox:nth-child(1) .box")).click();
            driver.findElement(By.cssSelector(".md-checkbox:nth-child(2) > label > .box")).click();
            driver.findElement(By.cssSelector(".md-checkbox:nth-child(7) .box")).click();
            driver.findElement(By.name("join")).click();
            assertThat(driver.findElement(By.cssSelector(".bold:nth-child(1)")).getText(), is("THANK YOU FOR CREATING AN ACCOUNT WITH BASKETBALL ENGLAND"));
        }
        */
    }

